default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  encoding: unicode

development:
  <<: *default
  database: moving_music_development

test:
  <<: *default
  database: moving_music_test

production:
  <<: *default
  database: moving_music_production
